// page action types
export const TITLE_CHANGE = 'TITLE_CHANGE';

// user profile action types
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

// fetch entries types
export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE';

// fetch single entry types
export const FETCH_ENTRY_REQUEST = 'FETCH_ENTRY_REQUEST';
export const FETCH_ENTRY_SUCCESS = 'FETCH_ENTRY_SUCCESS';
export const FETCH_ENTRY_FAILURE = 'FETCH_ENTRY_FAILURE';

// create entry action types
export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_FAILURE = 'CREATE_ENTRY_FAILURE';

// create entry action types
export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';
// edit entry action types
export const EDIT_ENTRY_REQUEST = 'EDIT_ENTRY_REQUEST';
export const EDIT_ENTRY_SUCCESS = 'EDIT_ENTRY_SUCCESS';
export const EDIT_ENTRY_FAILURE = 'EDIT_ENTRY_FAILURE';
